[package]
name = "starflow-client-app"
version = "0.0.1"
edition = "2024"

[dependencies]
glued = {path = "../../../glued"}
starflow-window = { path = "../window" }
starflow-render = { path = "../render" }

default = "0.1.2"
futures-lite = "2.6.0"
